spring:
  data:
    h2:
      console:
        enabled: true
        path: /h2-console
    datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:survey:db;
      username: sa
      password:
    jpa:
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          format_sql: true